#!/bin/bash
#
# This is free software, you can redistribute it and/or modify it under the
# terms of the GNU General Public License version 2 as published by the Free
# Software Foundation.
#

/usr/bin/rsync ${HOME}/Linux-Vim-Setup/ ${HOME}/ -rvzu --exclude ".git" --exclude "installer" --exclude "README" --exclude "*.swp" $@
