#!/bin/bash
#
# This is free software, you can redistribute it and/or modify it under the
# terms of the GNU General Public License version 2 as published by the Free
# Software Foundation.
#

if [ $1 ]; then
    echo -n "Copying to $1...";
    rsync ~/Linux-Vim-Setup/ $1:~/Linux-Vim-Setup/ -rvzlu > /dev/null;
    echo "done";
    echo "Running remote install";
    ssh $1 '~/Linux-Vim-Setup/installer'
else
    /usr/bin/rsync ${HOME}/Linux-Vim-Setup/ ${HOME}/ -vvzr --exclude ".git" --exclude "installer" --exclude "README" --exclude "*.swp" $@
    git config --global init.templatedir '~/.git-templates'
    git config --global alias.c checkout
    git config --global alias.ls "log --date=short --pretty=format:\"%C(yellow)%h\\ %cd%Cred%d\\ %Creset%s%Cblue\\ [%cn]\" --decorate"
    git config --global alias.ll "log --date=short --pretty=format:\"%C(yellow)%h\\ %cd%Cred%d\\ %Creset%s%Cblue\\ [%cn]\" --decorate --numstat"
    git config --global alias.la "!git config -l | grep alias | cut -c 7-"
    git config --global alias.b '!branches=`git branch`; while read -r branch; do clean=${branch//\*\ /}; description=`git config branch.$clean.description`; if [ "${branch::1}" == "*" ]; then printf "\033[0;31m%-16s\033[0m %s\n" "$branch" "$description"; else printf "  %-14s %s\n" "$branch" "$description"; fi; done <<< "$branches"'
    if [ -e ~/.ssh/authorized_keys ] && grep -q "no-agent-forwarding" ~/.ssh/authorized_keys
    then
        echo "*************************************************************"
        echo "*************************************************************"
        echo "****                                                     ****"
        echo "****  ~/.ssh/authorized_keys does not auto forward keys  ****"
        echo "****                                                     ****"
        echo "*************************************************************"
        echo "*************************************************************"
    fi
fi
