#!/bin/bash
#
# This is free software, you can redistribute it and/or modify it under the
# terms of the GNU General Public License version 2 as published by the Free
# Software Foundation.
#

if [ $1 ]; then
    echo -n "Copying to $1...";
    rsync ~/Linux-Vim-Setup/ $1:~/Linux-Vim-Setup/ -rvzlu > /dev/null;
    echo "done";
    echo "Running remote install";
    ssh $1 '~/Linux-Vim-Setup/installer'
else
    /usr/bin/rsync ${HOME}/Linux-Vim-Setup/ ${HOME}/ -vvzr --exclude ".git" --exclude "installer" --exclude "README" --exclude "*.swp" $@
    git config --global init.templatedir '~/.git-templates'
    if [ -e ~/.ssh/authorized_keys ] && grep -q "no-agent-forwarding" ~/.ssh/authorized_keys
    then
        echo "*************************************************************"
        echo "*************************************************************"
        echo "****                                                     ****"
        echo "****  ~/.ssh/authorized_keys does not auto forward keys  ****"
        echo "****                                                     ****"
        echo "*************************************************************"
        echo "*************************************************************"
    fi
fi
